name: Release

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:


# changeset release
# commit release version bump with no PR
# build
# create artifact
# create release (use changelog from changeset release)


jobs:
  windows-release:
    name: Windows Release
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # Grab all the git history for building changelog
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.14.x
          cache: npm

      - name: NPM Install
        run: npm install

      - name: Update Version Based on Changesets
        run: npm run version

      - name: Get Version
        id: get-version
        run: echo "::set-output name=version::$(node --print "require('./package.json').version")"

      - name: Print Version
        run: echo ${{ steps.get-version.outputs.version }}

      # - name: Build with Electron Builder
      #   # If the current push to master has no changesets then it is the merged PR for versioning and releasing
      #   # TODO: This assumes that there are not commits to master without changesets--fix this
      #   if: steps.changesets.outputs.hasChangesets == 'false'
      #   run: npm run build

      # - name: Create Release
      #   uses: ncipollo/release-action@v1.10.0
      #   if: steps.changesets.outputs.hasChangesets == 'false'
      #   with:
      #     tag: ${{ env.VERSION }}
      #     commit: main
      #     artifacts: "releases/**/*.exe, releases/**/*.exe.blockmap, releases/**/latest.yml"
      #     bodyFile: "CHANGELOG.md"
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     draft: true



        
