name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.14.x
          cache: npm
      
      - name: NPM Install
        run: npm install
      
      - name: Release
        run: npm run release
